title: Helby Studio
description: The mobile app studio that helps parents
remote_theme: sergiokopplin/indigo@1.0.1
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
